<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Color</name>
   <tag></tag>
   <elementGuidId>74384380-2454-43f5-bc97-7456afaa2b34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='productProperties']/div/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2.Colors.roboto-light.ng-scope</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>02cea767-0da9-415f-828c-20913a5b30e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>Color</value>
      <webElementGuid>2eedf7ab-c791-43c3-91ae-1a734fb93a16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Colors roboto-light ng-scope</value>
      <webElementGuid>4e84dcf0-75aa-43d7-b670-fd3803c7dd05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Color:</value>
      <webElementGuid>10e2864b-fa86-41b1-b032-54f0309f0f6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productProperties&quot;)/div[@class=&quot;colors ng-scope&quot;]/h2[@class=&quot;Colors roboto-light ng-scope&quot;]</value>
      <webElementGuid>ff13251d-8635-491b-aa62-6440f05e7261</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='productProperties']/div/h2</value>
      <webElementGuid>d3fc6818-e2b2-4c80-85aa-5af959d8c5ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SOLD OUT'])[2]/following::h2[1]</value>
      <webElementGuid>ce861934-1edc-4840-835f-b33e8291e6cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity:'])[1]/preceding::h2[1]</value>
      <webElementGuid>47e41a0a-7ea3-4613-b755-9207358a5dde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Warranty'])[1]/preceding::h2[1]</value>
      <webElementGuid>590da6f2-898b-4fd6-b901-c1e4a5757b9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/h2</value>
      <webElementGuid>7819b710-eac2-4d15-83d3-ba327216c122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Color:' or . = 'Color:')]</value>
      <webElementGuid>9a6d8c33-6f0a-4dc4-98a1-a1f04dbff000</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
